# Generated by Django 4.2.1 on 2023-06-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_entregable_estudiante_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='camada',
            field=models.IntegerField(default='00000'),
        ),
        migrations.AlterField(
            model_name='entregable',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entregable',
            name='fechaDeEntrega',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
